using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DataAccess; //CSV Tools
using IO = System.IO;
using System.Diagnostics;

//Title:  Grand Prix 4 GPxPatch Performance file generator.
//Author: AUS_Doug
//Desc:   Takes CSVs as input, and generates a GPxPatch 4.44 compatible Performance file for Grand Prix 4


namespace PerfFileGenerator
{
    class Program
    {
        static string appPath = IO.Directory.GetCurrentDirectory();

        //File names
        static String teamCSV, driverCSV, perfFileName;
        //Column names for Team, Engine, Power, Reliability
        static String teamNameCol, engineCol, racePowerCol, qualPowerCol, reliabilityCol;
        //Column names for Driver, Number, Grip, Nationality, Tag
        static String driverCol, driverNumCol, raceGripCol, raceGripVarCol, qualGripCol, qualGripVarCol, driverNatCol, driverTagCol;

        //Do we have; Driver Numbers? Driver Nationalities? 3-Letter Driver Codes?
        static Boolean driverNumbers, driverNat, driverTag;

        //File names
        static int teamNameColInt, engineColInt, racePowerColInt, qualPowerColInt, reliabilityColInt, driverColInt, driverNumColInt, raceGripColInt, raceGripVarColInt, qualGripColInt, qualGripVarColInt, driverNatColInt, driverTagColInt;

        //Accepts up to three arguments: CSV containing Team info; CSV containing Driver info; Output file name (Optional)
        static void Main(string[] args)
        {

            //Setup logging of the console
            consoleLogger();
            iniLoader();
            IO.StreamWriter writer;
            try {
                MutableDataTable team = DataTable.New.ReadCsv(teamCSV);
                MutableDataTable driver = DataTable.New.ReadCsv(driverCSV);

                //Gets ints from our column names
                teamNameColInt = team.GetColumnIndex(teamNameCol);
                engineColInt = team.GetColumnIndex(engineCol);
                racePowerColInt = team.GetColumnIndex(racePowerCol);
                qualPowerColInt = team.GetColumnIndex(qualPowerCol);
                reliabilityColInt = team.GetColumnIndex(reliabilityCol);
                driverColInt = driver.GetColumnIndex(driverCol);
                driverNumColInt = driver.GetColumnIndex(driverNumCol);
                raceGripColInt = driver.GetColumnIndex(raceGripCol);
                raceGripVarColInt = driver.GetColumnIndex(raceGripVarCol);
                qualGripColInt = driver.GetColumnIndex(qualGripCol);
                qualGripVarColInt = driver.GetColumnIndex(qualGripVarCol);
                driverNatColInt = driver.GetColumnIndex(driverNatCol);
                driverTagColInt = driver.GetColumnIndex(driverTagCol);

                int teamIndex = 0, driver1Index = 0, driver2Index = 1;

                if (perfFileName.Length > 0)
                {
                    writer = new IO.StreamWriter(perfFileName + ".txt");
                }
                else
                {
                    writer = new IO.StreamWriter("Performance.txt");
                }

                writer.WriteLine("** Grand Prix 4 Performance File - Generated by GP4PerfGen v1.0 **");
                writer.WriteLine("[File]");
                writer.WriteLine("Version=213");

                foreach (Row row in team.Rows)
                {
                    if (teamIndex < 10)
                    {
                        writer.WriteLine("[Team #0" + teamIndex + "]");
                    }
                    else
                    {
                        writer.WriteLine("[Team #" + teamIndex + "]");
                    }
                    //Team name and Engine
                    writer.WriteLine("Name=" + team.Columns[teamNameColInt].Values[teamIndex] + "," + team.Columns[engineColInt].Values[teamIndex] + "");
                    //Race BHP, Qual BHP, Reliability
                    writer.WriteLine("Performance=" + team.Columns[racePowerColInt].Values[teamIndex] + "," + team.Columns[qualPowerColInt].Values[teamIndex] + "," + team.Columns[reliabilityColInt].Values[teamIndex] + "");
                    //Driver 1
                    writer.WriteLine("First Driver=" + driver.Columns[driverNumColInt].Values[driver1Index] + "," + driver.Columns[driverColInt].Values[driver1Index] + "," + driver.Columns[raceGripColInt].Values[driver1Index] + "," + driver.Columns[raceGripVarColInt].Values[driver1Index] + "," + driver.Columns[qualGripColInt].Values[driver1Index] + "," + driver.Columns[qualGripVarColInt].Values[driver1Index] + "," + driver.Columns[driverNatColInt].Values[driver1Index] + "," + driver.Columns[driverTagColInt].Values[driver1Index] + "");
                    //Driver 2
                    writer.WriteLine("Second Driver=" + driver.Columns[driverNumColInt].Values[driver2Index] + "," + driver.Columns[driverColInt].Values[driver2Index] + "," + driver.Columns[raceGripColInt].Values[driver2Index] + "," + driver.Columns[raceGripVarColInt].Values[driver2Index] + "," + driver.Columns[qualGripColInt].Values[driver2Index] + "," + driver.Columns[qualGripVarColInt].Values[driver2Index] + "," + driver.Columns[driverNatColInt].Values[driver2Index] + "," + driver.Columns[driverTagColInt].Values[driver2Index] + "");
                    teamIndex++;
                    driver1Index = driver1Index + 2;
                    driver2Index = driver2Index + 2;
                }

                writer.Close();
            }
            catch(IndexOutOfRangeException ex)
            {
                Trace.WriteLine("An index was out of range!");
                Trace.WriteLine("Have you got enough Drivers to fill your Teams?");
            }
            catch (IO.FileNotFoundException ex)
            {
                Trace.WriteLine("A file was missing.");
                Trace.WriteLine(ex.Message);
            }     
            Trace.WriteLine("-----Ending Session at " + DateTime.Now + "-----\n");

        }

        private static void consoleLogger()
        {
            Trace.Listeners.Clear();

            TextWriterTraceListener twtl = new TextWriterTraceListener(appPath + "/PerfGenerator.log", AppDomain.CurrentDomain.FriendlyName);
            twtl.Name = "TextLogger";
            twtl.TraceOutputOptions = TraceOptions.ThreadId | TraceOptions.DateTime;

            ConsoleTraceListener ctl = new ConsoleTraceListener(false);
            ctl.TraceOutputOptions = TraceOptions.DateTime;

            Trace.Listeners.Add(twtl);
            Trace.Listeners.Add(ctl);
            Trace.AutoFlush = true;

            Trace.WriteLine("-----Starting Session at " + DateTime.Now + "-----\n");

        }

        //Method to check for - and read from - the settings.ini file
        private static void iniLoader()
        {
            Trace.WriteLine("---INI DATA BEGIN:---\n");
            if (IO.File.Exists(appPath + "/Settings.ini\n"))
            {
                Trace.WriteLine("INI File Found\n");

                #region Get file names
                teamCSV = INIFile.ReadValue("Files", "Team CSV", appPath + "/Settings.ini");
                Trace.WriteLine("'Teams CSV' name read as " + teamCSV + "\n");
                driverCSV = INIFile.ReadValue("Files", "Driver CSV", appPath + "/Settings.ini");
                Trace.WriteLine("'Drivers CSV' name read as " + driverCSV + "\n");
                perfFileName = INIFile.ReadValue("Files", "Perf File Name", appPath + "/Settings.ini");
                Trace.WriteLine("'Perf File' Name name read as " + perfFileName + "\n");
                #endregion


                #region Boolenas
                //Boolean.TryParse((INIFile.ReadValue("Settings", "Have Driver Numbers", appPath + "/Settings.ini")), out driverNumbers);
                //Trace.WriteLine("'Have Driver Numbers' read as " + driverNumbers + "\n");
                //Boolean.TryParse((INIFile.ReadValue("Settings", "Have Driver Nationality", appPath + "/Settings.ini")), out driverNat);
                //Trace.WriteLine("'Have Driver Numbers' read as " + driverNat + "\n");
                //Boolean.TryParse((INIFile.ReadValue("Settings", "Have Driver Tags", appPath + "/Settings.ini")), out driverTag);
                //Trace.WriteLine("'Have Driver Numbers' read as " + driverTag + "\n");
                #endregion

                #region Team Info
                teamNameCol = INIFile.ReadValue("Team", "Team Name", appPath + "/Settings.ini");
                Trace.WriteLine("'Team Name' Column read as " + teamNameCol + "\n");
                engineCol = INIFile.ReadValue("Team", "Engine", appPath + "/Settings.ini");
                Trace.WriteLine("'Engine' Column read as " + engineCol + "\n");
                racePowerCol = INIFile.ReadValue("Team", "Race Power", appPath + "/Settings.ini");
                Trace.WriteLine("'Race Power' Column read as " + racePowerCol + "\n");
                qualPowerCol = INIFile.ReadValue("Team", "Qualifying Power", appPath + "/Settings.ini");
                Trace.WriteLine("'Qual Power' Column read as " + qualPowerCol + "\n");
                reliabilityCol = INIFile.ReadValue("Team", "Reliability", appPath + "/Settings.ini");
                Trace.WriteLine("'Reliability' Column read as " + reliabilityCol + "\n");
                #endregion

                #region Driver Info
                driverCol = INIFile.ReadValue("Driver", "Driver Name", appPath + "/Settings.ini");
                Trace.WriteLine("'Driver Name' Column read as " + driverCol + "\n");
                driverNumCol = INIFile.ReadValue("Driver", "Driver Number", appPath + "/Settings.ini");
                Trace.WriteLine("'Driver Number' Column read as " + driverNumCol + "\n");
                raceGripCol = INIFile.ReadValue("Driver", "Race Grip", appPath + "/Settings.ini");
                Trace.WriteLine("'Race Grip' Column read as " + raceGripCol + "\n");
                raceGripVarCol = INIFile.ReadValue("Driver", "Race Grip Var", appPath + "/Settings.ini");
                Trace.WriteLine("'Race Grip Var' Column read as " + raceGripVarCol + "\n");
                qualGripCol = INIFile.ReadValue("Driver", "Qualifying Grip", appPath + "/Settings.ini");
                Trace.WriteLine("'Qualifying Grip' Column read as " + qualGripCol + "\n");
                qualGripVarCol = INIFile.ReadValue("Driver", "Qualifying Grip Var", appPath + "/Settings.ini");
                Trace.WriteLine("'Qualifying Grip Var' Column read as " + qualGripVarCol + "\n");
                driverNatCol = INIFile.ReadValue("Driver", "Driver Nationality", appPath + "/Settings.ini");
                Trace.WriteLine("'Driver Nationality' Column Column read as " + driverNatCol + "\n");
                driverTagCol = INIFile.ReadValue("Driver", "Driver Tag", appPath + "/Settings.ini");
                Trace.WriteLine("'Driver Tag' Column Column read as " + driverTagCol + "\n");

                #endregion
            }
            #region No INI
            else
            {
                Trace.WriteLine("No INI File Found\n");
                Trace.WriteLine("Generating Default Values and Reloading");
                INIFile.WriteValue("Files", "Team CSV", "Teams.csv", appPath + "/Settings.ini");
                INIFile.WriteValue("Files", "Driver CSV", "Drivers.csv", appPath + "/Settings.ini");
                INIFile.WriteValue("Files", "Perf File Name", "Performance", appPath + "/Settings.ini");
                //INIFile.WriteValue("Settings", "Have Driver Numbers", "False", appPath + "/Settings.ini");
                //INIFile.WriteValue("Settings", "Have Driver Nationality", "False", appPath + "/Settings.ini");
                //INIFile.WriteValue("Settings", "Have Driver Tags", "False", appPath + "/Settings.ini");
                INIFile.WriteValue("Team", "Team Name", "Team Name", appPath + "/Settings.ini");
                INIFile.WriteValue("Team", "Engine", "Engine", appPath + "/Settings.ini");
                INIFile.WriteValue("Team", "Race Power", "Race Power", appPath + "/Settings.ini");
                INIFile.WriteValue("Team", "Qualifying Power", "Qualifying Power", appPath + "/Settings.ini");
                INIFile.WriteValue("Team", "Reliability", "Reliability", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Driver Name", "Driver", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Driver Number", "Driver Number", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Race Grip", "Base Race Grip", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Race Grip Var", "Race Grip Variance", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Qualifying Grip", "Base Qualifying Grip", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Qualifying Grip Var", "Qualifying Grip Variance", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Driver Nationality", "Nationality", appPath + "/Settings.ini");
                INIFile.WriteValue("Driver", "Driver Tag", "Tag", appPath + "/Settings.ini");
                Trace.WriteLine("Options set to default values......\n");
                Trace.WriteLine("Reloading INI");
                iniLoader();
                #endregion
            }

            Trace.WriteLine("---INI DATA END---\n");

        }

        private static void stringToInt()
        {

        }

    }
}
